#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python main.py monitoring \
  --kafka_servers ${KAFKA_HOST} \
  --kafka_ssl_cafile=${KAFKA_SSL_CAFILE} \
  --kafka_ssl_certfile=${KAFKA_SSL_CERTFILE} \
  --kafka_ssl_keyfile=${KAFKA_SSL_KEYFILE}
